name: vit_vtop
description: "Dart package that provides Dart bindings for the VTOP rust library"
version: 0.0.1
repository: https://github.com/VITAP-Student-Project/vit_vtop

environment:
  sdk: ^3.7.2

dependencies:
  ffi: ^2.1.4
  flutter_rust_bridge: ^2.11.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dotenv: ^4.2.0
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  ffigen: ^19.0.0
  build_runner: ^2.4.8
  freezed: ^3.1.0
  json_serializable: ^6.9.4
