// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'session_manager.dart';
import 'vtop_config.dart';

// These functions are ignored because they are not marked as `pub`: `extract_captcha_data`, `extract_csrf_token`, `get_login_page_error`, `get_regno`, `load_initial_page`, `load_login_page`, `make_client`, `perform_login`, `solve_captcha`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopClient>>
abstract class VtopClient implements RustOpaqueInterface {
  Future<VtopResultVecAttendanceRecord> getAttendance({
    required String semesterId,
  });

  Future<VtopResultVecAttendanceDetailRecord> getAttendanceDetail({
    required String semesterId,
    required String courseId,
    required String courseType,
  });

  Future<VtopResultVecBiometricRecord> getBiometricData({required String date});

  Future<VtopResultVecU8> getCookie();

  Future<VtopResultVecPerExamScheduleRecord> getExamSchedule({
    required String semesterId,
  });

  Future<VtopResultFacultyDetails> getFacultyData({required String empId});

  Future<VtopResultGetFaculty> getFacultySearch({required String searchTerm});

  Future<VtopResultVecU8> getHostelLeavePdf({required String leaveId});

  Future<VtopResultHostelLeaveData> getHostelLeaveReport();

  Future<VtopResultVecU8> getHostelOutingPdf({required String bookingId});

  Future<VtopResultHostelOutingData> getHostelReport();

  Future<VtopResultVecMarksRecord> getMarks({required String semesterId});

  Future<VtopResultSemesterData> getSemesters();

  Future<VtopResultVecTimetableSlot> getTimetable({required String semesterId});

  Future<bool> isAuthenticated();

  Future<VtopResult> login();

  Future<VtopResultString> submitOutingForm({
    required String purposeOfVisit,
    required String outingDate,
    required String contactNumber,
    required String outPlace,
    required String outTime,
  });

  static Future<VtopClient> withConfig({
    required VtopConfig config,
    required SessionManager session,
    required String username,
    required String password,
  }) => RustLib.instance.api.crateApiVtopVtopClientVtopClientWithConfig(
    config: config,
    session: session,
    username: username,
    password: password,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < () >>>
abstract class VtopResult implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < FacultyDetails >>>
abstract class VtopResultFacultyDetails implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < GetFaculty >>>
abstract class VtopResultGetFaculty implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < HostelLeaveData >>>
abstract class VtopResultHostelLeaveData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < HostelOutingData >>>
abstract class VtopResultHostelOutingData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < SemesterData >>>
abstract class VtopResultSemesterData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < String >>>
abstract class VtopResultString implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < Vec < AttendanceDetailRecord > >>>
abstract class VtopResultVecAttendanceDetailRecord
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < Vec < AttendanceRecord > >>>
abstract class VtopResultVecAttendanceRecord implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < Vec < BiometricRecord > >>>
abstract class VtopResultVecBiometricRecord implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < Vec < MarksRecord > >>>
abstract class VtopResultVecMarksRecord implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < Vec < PerExamScheduleRecord > >>>
abstract class VtopResultVecPerExamScheduleRecord
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < Vec < TimetableSlot > >>>
abstract class VtopResultVecTimetableSlot implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < Vec < u8 > >>>
abstract class VtopResultVecU8 implements RustOpaqueInterface {}
