// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;
part 'attendance.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

@freezed
@meta.immutable
sealed class AttendanceDetailRecord with _$AttendanceDetailRecord {
  const factory AttendanceDetailRecord({
    required String serial,
    required String date,
    required String slot,
    required String dayTime,
    required String status,
    required String remark,
  }) = _AttendanceDetailRecord;
}

/// AttendanceRecord -> This is a basic single attendance data row that you see in attendance page
/// AttendanceData -> This is a list of AttendanceRecord(s)
/// AttendanceDetailRecord -> This is the more detailed attendance data that you see when the eye icon is pressed
/// AttendanceDetail -> This is a list of AttendanceDetailRecord(s)
@freezed
@meta.immutable
sealed class AttendanceRecord with _$AttendanceRecord {
  const factory AttendanceRecord({
    required String serial,
    required String category,
    required String courseName,
    required String courseCode,
    required String courseType,
    required String facultyDetail,
    required String classesAttended,
    required String totalClasses,
    required String attendancePercentage,
    required String attendenceFatCat,
    required String debarStatus,
    required String courseId,
  }) = _AttendanceRecord;
}
